<a href="https://colab.research.google.com/github/KringeKrimson/Pytorch-Basics/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

#Tensors
- A torch. Tensor is multidimensional matrix constaining elements of single data type.
- It is similar to Numpy Arrays, but more adjusted to work better in CPUs and GPUs.
- Its default data type is float32.

In [15]:
tensor_2d = torch.randn(3,4)
print(tensor_2d.dtype)

torch.float32


In [11]:
numpy_array = np.random.rand(3,4)
numpy_array

array([[0.21194713, 0.46209189, 0.60570029, 0.63308933],
       [0.78254921, 0.92781072, 0.29383848, 0.51621395],
       [0.08582528, 0.86524603, 0.59971352, 0.01627598]])

#Note
Here the dtype is float64 because the default for the numpy is float64.

In [12]:
## Converting numpy array to tensor
to_tensor = torch.tensor(numpy_array)
to_tensor

tensor([[0.2119, 0.4621, 0.6057, 0.6331],
        [0.7825, 0.9278, 0.2938, 0.5162],
        [0.0858, 0.8652, 0.5997, 0.0163]], dtype=torch.float64)

#Further functionalities:
Check: https://pytorch.org/docs/stable/tensors.html

#Tensor Operations

In [16]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
my_torch[0,3]

tensor(3)

In general the operations are very similar to Numpy.


#View vs Reshape
They may look similar but are quite different. Refer to the documentation

In [22]:
my_torch2 = torch.arange(10).view(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
my_torch2[:,1]

tensor([1, 6])

#Tensor Math Operations
- Add, Subtract, Multiply, Division, Remainders, Exponents
- Shorthand and Longhand
- Reassignment

In [24]:
tensor_a = torch.tensor([1,2,3,4,5])
tensor_b = torch.tensor([5,4,3,2,1])
#Addition shorthand
tensor_a + tensor_b

tensor([6, 6, 6, 6, 6])

In [25]:
# Addition Longhand
torch.add(tensor_a,tensor_b)

tensor([6, 6, 6, 6, 6])

In [26]:
#Another way for Addition Longhand
tensor_a.add(tensor_b)

tensor([6, 6, 6, 6, 6])

In [ ]:
#Reassignment
tensor_a.add_(tensor_b) # this is equal to "tensor_a = tensor_a + tensor_b"